UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.userTable}
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: address
        AttributeType: S
    KeySchema:
      - AttributeName: address
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
      WriteCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES

RequestTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.requestsTable}
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
      WriteCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES

ConnectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.connectionsTable}
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: reverse
        KeySchema:
          - AttributeName: sk
            KeyType: HASH
          - AttributeName: pk
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
          WriteCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
    ProvisionedThroughput:
      ReadCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
      WriteCapacityUnits: ${self:custom.tableThroughputs.${self:provider.stage}}
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
